jwt:
  secret: absfol7814lqmva7891294nn9asa783nr293urnq9adm38ry2
  expire: 30000000

users:
  starter:
    enabled: true
    data:
      patients:
        - username: 'Client123321'
          password: 'Client123321_'
          email: 'client_1@rental.com'
          first-name: 'Bob'
          last-name: 'Dylan'
          phone-number: '887102990'
          national-id: '92102005998'
          dateOfBirth: '1982-02-17'
          enabled: true
      doctors:
        - username: 'Doctor123321'
          password: 'Doctor123321_'
          email: 'doctor_1@rental.com'
          first-name: 'Bob'
          last-name: 'Dylan'
          phone-number: '887102990'
          national-id: '92102005998'
          dateOfBirth: '1982-02-17'
          enabled: true
          specialization: 'Psychiatry'
          workingAsDoctorSince: '1999-02-17'
      admins:
        - username: 'Admin123321'
          password: 'Admin123321_'
          email: 'admin_1@rental.com'
          first-name: 'Bob'
          last-name: 'Dylan'
          phone-number: '887102990'
          national-id: '92102005998'
          dateOfBirth: '1982-02-17'
          enabled: true