server:
  port: 8080
  error:
    include-message: always

management:
  server:
    port: 9080

logging:
  level:
    root: INFO

# Configuration regarding usage in memory h2 database
spring:
  thymeleaf:
    check-template-location: false
  profiles:
    default: DEFAULT
    active: DEFAULT
    group:
      DEFAULT: POSTGRES
      DEVLOCAL: H2
  jpa:
    show-sql: ${SHOW_SQL:true}

users:
  starter:
    enabled: false