jwt:
  secret: absfol7814lqmva7891294nn9asa783nr293urnq9adm38ry2

users:
  starter:
    enabled: true
    data:
      users:
        - username: 'Admin123321'
          password: 'Admin123321_'
          email: 'admin_1@rental.com'
          first-name: 'Bob'
          last-name: 'Dylan'
          phone-number: '887102990'
          national-id: '92102005998'
          enabled: true